/*
 * This file was automatically generated by EvoSuite
 * Fri Jan 03 10:10:42 GMT 2025
 */

package ds.EvoSuiteTest;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import ds.weekday;
import java.util.NoSuchElementException;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, useJEE = true) 
public class Evo extends weekday_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      int int0 = weekday.getWeekday(1, 1, 0);
      assertEquals(7, int0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      int int0 = weekday.getWeekday(2202, 2, 5);
      assertEquals(5, int0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      int int0 = weekday.getWeekday(627, 10, 627);
      assertEquals((-3), int0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      int int0 = weekday.getWeekday(12, 761, 359);
      assertEquals((-2), int0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      int int0 = weekday.getWeekday(10018, 519, 1028);
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      int int0 = weekday.getWeekday((-4495), (-4495), (-4495));
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      int int0 = weekday.getWeekday(3512, 3512, (-4495));
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      int int0 = weekday.getWeekday(0, (-1691), (-1));
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      weekday weekday0 = new weekday();
  }

  @Test(timeout = 4000)
  public void test9()  throws Throwable  {
      String[] stringArray0 = new String[0];
      // Undeclared exception!
      try { 
        weekday.main(stringArray0);
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.Scanner", e);
      }
  }
}
